# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpctransport.grpcnn_pb2 as grpcnn__pb2


class GrpcServiceNNStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingNN = channel.unary_unary(
                '/grpctransport.GrpcServiceNN/PingNN',
                request_serializer=grpcnn__pb2.EmptyMessageNN.SerializeToString,
                response_deserializer=grpcnn__pb2.EmptyMessageNN.FromString,
                )
        self.GetFace = channel.unary_unary(
                '/grpctransport.GrpcServiceNN/GetFace',
                request_serializer=grpcnn__pb2.GetFaceRequest.SerializeToString,
                response_deserializer=grpcnn__pb2.GetFaceResponse.FromString,
                )
        self.PredictFromBytes = channel.unary_unary(
                '/grpctransport.GrpcServiceNN/PredictFromBytes',
                request_serializer=grpcnn__pb2.PredictFromBytesRequest.SerializeToString,
                response_deserializer=grpcnn__pb2.PhotosToModelResponse.FromString,
                )
        self.LoadWeigths = channel.unary_unary(
                '/grpctransport.GrpcServiceNN/LoadWeigths',
                request_serializer=grpcnn__pb2.EmptyMessageNN.SerializeToString,
                response_deserializer=grpcnn__pb2.EmptyMessageNN.FromString,
                )
        self.FitAllToModel = channel.unary_unary(
                '/grpctransport.GrpcServiceNN/FitAllToModel',
                request_serializer=grpcnn__pb2.FitAllToModelRequest.SerializeToString,
                response_deserializer=grpcnn__pb2.EmptyMessageNN.FromString,
                )
        self.GetStatusOfFit = channel.unary_unary(
                '/grpctransport.GrpcServiceNN/GetStatusOfFit',
                request_serializer=grpcnn__pb2.EmptyMessageNN.SerializeToString,
                response_deserializer=grpcnn__pb2.FitStatusResponseNN.FromString,
                )
        self.CutBackgroundAndValidFace = channel.unary_unary(
                '/grpctransport.GrpcServiceNN/CutBackgroundAndValidFace',
                request_serializer=grpcnn__pb2.CutBackgroundAndValidFaceRequest.SerializeToString,
                response_deserializer=grpcnn__pb2.CutBackgroundAndValidFaceResponse.FromString,
                )
        self.ExitApp = channel.unary_unary(
                '/grpctransport.GrpcServiceNN/ExitApp',
                request_serializer=grpcnn__pb2.EmptyMessageNN.SerializeToString,
                response_deserializer=grpcnn__pb2.EmptyMessageNN.FromString,
                )


class GrpcServiceNNServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingNN(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictFromBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadWeigths(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FitAllToModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatusOfFit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CutBackgroundAndValidFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceNNServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingNN': grpc.unary_unary_rpc_method_handler(
                    servicer.PingNN,
                    request_deserializer=grpcnn__pb2.EmptyMessageNN.FromString,
                    response_serializer=grpcnn__pb2.EmptyMessageNN.SerializeToString,
            ),
            'GetFace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFace,
                    request_deserializer=grpcnn__pb2.GetFaceRequest.FromString,
                    response_serializer=grpcnn__pb2.GetFaceResponse.SerializeToString,
            ),
            'PredictFromBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictFromBytes,
                    request_deserializer=grpcnn__pb2.PredictFromBytesRequest.FromString,
                    response_serializer=grpcnn__pb2.PhotosToModelResponse.SerializeToString,
            ),
            'LoadWeigths': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadWeigths,
                    request_deserializer=grpcnn__pb2.EmptyMessageNN.FromString,
                    response_serializer=grpcnn__pb2.EmptyMessageNN.SerializeToString,
            ),
            'FitAllToModel': grpc.unary_unary_rpc_method_handler(
                    servicer.FitAllToModel,
                    request_deserializer=grpcnn__pb2.FitAllToModelRequest.FromString,
                    response_serializer=grpcnn__pb2.EmptyMessageNN.SerializeToString,
            ),
            'GetStatusOfFit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatusOfFit,
                    request_deserializer=grpcnn__pb2.EmptyMessageNN.FromString,
                    response_serializer=grpcnn__pb2.FitStatusResponseNN.SerializeToString,
            ),
            'CutBackgroundAndValidFace': grpc.unary_unary_rpc_method_handler(
                    servicer.CutBackgroundAndValidFace,
                    request_deserializer=grpcnn__pb2.CutBackgroundAndValidFaceRequest.FromString,
                    response_serializer=grpcnn__pb2.CutBackgroundAndValidFaceResponse.SerializeToString,
            ),
            'ExitApp': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitApp,
                    request_deserializer=grpcnn__pb2.EmptyMessageNN.FromString,
                    response_serializer=grpcnn__pb2.EmptyMessageNN.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpctransport.GrpcServiceNN', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcServiceNN(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingNN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpctransport.GrpcServiceNN/PingNN',
            grpcnn__pb2.EmptyMessageNN.SerializeToString,
            grpcnn__pb2.EmptyMessageNN.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpctransport.GrpcServiceNN/GetFace',
            grpcnn__pb2.GetFaceRequest.SerializeToString,
            grpcnn__pb2.GetFaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictFromBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpctransport.GrpcServiceNN/PredictFromBytes',
            grpcnn__pb2.PredictFromBytesRequest.SerializeToString,
            grpcnn__pb2.PhotosToModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadWeigths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpctransport.GrpcServiceNN/LoadWeigths',
            grpcnn__pb2.EmptyMessageNN.SerializeToString,
            grpcnn__pb2.EmptyMessageNN.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FitAllToModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpctransport.GrpcServiceNN/FitAllToModel',
            grpcnn__pb2.FitAllToModelRequest.SerializeToString,
            grpcnn__pb2.EmptyMessageNN.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatusOfFit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpctransport.GrpcServiceNN/GetStatusOfFit',
            grpcnn__pb2.EmptyMessageNN.SerializeToString,
            grpcnn__pb2.FitStatusResponseNN.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CutBackgroundAndValidFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpctransport.GrpcServiceNN/CutBackgroundAndValidFace',
            grpcnn__pb2.CutBackgroundAndValidFaceRequest.SerializeToString,
            grpcnn__pb2.CutBackgroundAndValidFaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExitApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpctransport.GrpcServiceNN/ExitApp',
            grpcnn__pb2.EmptyMessageNN.SerializeToString,
            grpcnn__pb2.EmptyMessageNN.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
